version: "3"

networks:
  fs73dxp1:
    external:
      name: fs73dxp1

services:
  omnidb:
    #build: .
    image: taivokasper/omnidb
    container_name: liferay_omnidb
    ports:
      #- "8000:8000"
      - "8000:8080"
      - "25482:25482"
    networks:
       - fs73dxp1